EXE = reversi

all: build

build: 
	@cd src && $(MAKE)
	@cp -f src/$(EXE) ./

check: build
	@cd tests && $(MAKE)

clean:
	@cd src && $(MAKE) clean
	@cd tests && $(MAKE) clean
	@rm -f $(EXE)

help:
	@echo "Usage:"
	@echo " make [all]\t\tBuild the software"
	@echo " make build\t\tBuild the software"
	@echo " make check\t\tRun all the tests"
	@echo " make clean\t\tRemove all files generated by make"
	@echo " make help\t\tDisplay this help"

.PHONY: all build check clean help